### ISSUE TITLE
More firmware on official post

### ISSUE THREAD

**Issue by chronoss09** [B-Dem/PPPwnUI#3]
Can u add these new version on your GUI please ?
FW 8.50
FW 9.00
FW 9.03 / 9.04
FW 9.50 / 9.60
FW 10.00 / 10.01
FW 10.50 / 10.70 / 10.71
FW 11.00

I see the official version have all of these firmware...

**Comment by B-Dem** [comment]
Update Will come soon and other Firmware will be added !

**Comment by B-Dem** [comment]
2.0 is now out !
Enjoy !
