### ISSUE TITLE
Goldhen did not upload

### ISSUE THREAD

**Issue by defcore22** [B-Dem/PPPwnUI#8]
Hi I succesfully load payload but goldhen did not uplaoad from the USB what can I do? is there any way to upload it with this tool?

**Comment by B-Dem** [comment]
Hey did you fixed the issue ?
If not just moove the goldhen.bin into the root of a USB drive.

**Comment by defcore22** [comment]
Yes I fixed

**Comment by Abidth** [comment]
Can you help me ?!

**Comment by defcore22** [comment]
For what?

**Comment by defcore22** [comment]
> Can you help me ?!

For what?

**Comment by Abidth** [comment]
I delete data and cookies of browser PS4 and USB was inside it .. the browser not responding

**Comment by defcore22** [comment]
> I delete data and cookies of browser PS4 and USB was inside it .. the browser not responding 

So you jailbreak the PS4 but the Internet does not work?

**Comment by Abidth** [comment]
No i already disconnected ..but the page to get goldHen disappeared

**Comment by defcore22** [comment]
What's your ps4 version? and which technic you using now?

**Comment by Abidth** [comment]
Version 9.00 
No technique ..i'm stuck

**Comment by defcore22** [comment]
https://www.youtube.com/watch?v=yVFbo23BCK4 did you watch this?

**Comment by Abidth** [comment]
https://youtu.be/fJyqf4xwIzA?si=zqu9l_kNh_4iQNzi no i watch this and it fixed ..tysm👍👍
