### ISSUE TITLE
Payload not injecting (using ver.2.1)

### ISSUE THREAD

**Issue by ukyo13** [B-Dem/PPPwnUI#9]
I tried using the newly released ver 2.1
When I set it to just PPPwn 11.00 and the console says "Done", it'll show the notification "PPPwned" in my PS4 but no Goldhen Notification
When I set it to PPPwn Goldhen 11.00, it'll no longer show the "PPPwned" too.
I made sure that the goldhen.bin was loaded in the usb drive that's plugged in the PS4 and I've tried both exFAT and FAT32 formats, still no luck

**Comment by B-Dem** [comment]
Hi ! 
Seems like Windows Issue.
Did your Stage 4 take some time to inject the payload ? (Like 30 seconds - 1 minute ?)
Got the same thing with my ps4 I tried with linux and it worked perfectly.

**Comment by B-Dem** [comment]
Note also that currently PPPwnUI don't work on linux 
I gotta fix it asap
